awsRegion: ${aws_region}

autoDiscovery:
  clusterName: ${cluster_name}
extraArgs:
  aws-use-static-instance-list: true

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
